---
- hosts: local
  connection: local

  vars_files:
    - vars/dev.yml
    - vars/apache.yml
    - vars/php.yml

  handlers:
    - name: restart apache
      become: yes
      command: apachectl restart
    - name: restart dnsmasq
      become: yes
      command: brew services restart dnsmasq
    - name: restart mysql
      command: brew services restart homebrew/versions/mysql56
    - name: restart redis
      command: brew services restart redis
    - name: restart elasticsearch
      command: brew services restart homebrew/versions/elasticsearch17

  tasks:
    ############################################################################
    # software                                                                 #
    ############################################################################

    - name: Tap homebrew repositories
      homebrew_tap: tap={{ item }}
      with_items: "{{ homebrew_taps }}"

    - name: Install apps via `brew cask`
      homebrew_cask: name={{ item }} install_options="appdir={{ homebrew_cask_appdir }}"
      with_items: "{{ homebrew_cask_apps }}"

    - name: Install configured homebrew packages
      homebrew: name={{ item }} state=latest
      with_items: "{{ homebrew_packages }}"

    - name: Install npm ecosystem
      npm: name={{ item }} global=yes state=present
      with_items: "{{ npm_packages }}"

    - name: Install gem ecosystem
      gem: name={{ item }} state=present user_install=no
      with_items: "{{ gem_packages }}"

    ############################################################################
    # dnsmasq config                                                           #
    ############################################################################

    - name: Add *.dev resolver
      become: yes
      lineinfile:
        state: present
        line: nameserver 127.0.0.1
        create: yes
        dest: /etc/resolver/dev
        owner: root
        group: wheel

    - name: Resolve *.dev to localhost
      lineinfile:
        state: present
        line: address=/.dev/127.0.0.1
        create: yes
        dest: /usr/local/etc/dnsmasq.conf
      notify: restart dnsmasq

    ############################################################################
    # Apache config                                                            #
    ############################################################################

    - name: Create projects directory
      file:
        path=~/Sites
        state=directory

    - name: Configure Apache
      become: yes
      lineinfile:
        dest: /etc/apache2/httpd.conf
        regexp: {{ item.regexp }}
        line: {{ item.line }}
        state: present
      with_items: "{{ apache_configuration_items }}"
      notify: restart apache


    - name: Add apache vhosts configuration
      become: yes
      template:
        src: "vhosts.conf.j2"
        dest: "/etc/apache2/extra/httpd-vhosts.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart apache
      when: apache_create_vhosts

    ############################################################################
    # PHP config                                                               #
    ############################################################################

    - name: PHP configuration
      ini_file:
        dest: /usr/local/etc/php/5.6/php.ini
        section: {{ item.section }}
        option: {{ item.option }}
        value: {{ item.value }}
      with_items: "{{ php_configuration_items }}"
      notify: restart apache
