---
- hosts: local
  connection: local

  vars_files:
    - vars/brew/taps.yml
    - vars/brew/brew.yml
    - vars/brew/cask.yml
    - vars/brew/services.yml
    - vars/php.yml
    - vars/mac_apple_store.yml

  roles:
    - name: geerlingguy.mas
      when: mas_installed_apps
      ignore_errors: yes

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - vars/override.yml

  tasks:
    - include: tasks/install.yml
    - include: tasks/config.yml
