---
- name: "Playing main macOS setup - apps and services from brew"
  hosts: localhost
  connection: local

  vars_files:
    - vars/php.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - vars/override.yml

  tasks:
    - include: tasks/install.yml
