---
- hosts: local
  connection: local

  vars_files:
    - vars/main.yml

  tasks:
    - name: Tap homebrew repositories
      homebrew_tap: tap={{ item }}
      with_items: "{{ homebrew_taps }}"

    - name: Install apps via `brew cask`
      homebrew_cask: name={{ item }}
      with_items: "{{ homebrew_cask_apps }}"

    - name: Install configured homebrew packages
      homebrew: name={{ item }} state=latest
      with_items: "{{ homebrew_packages }}"

    - name: Install npm ecosystem
      npm: name={{ item }} global=yes state=present
      with_items: "{{ npm_packages }}"

    - name: Install gem ecosystem
      gem: name={{ item }} state=present user_install=no
      with_items: "{{ gem_packages }}"
