---
- hosts: local
  connection: local

  vars_files:
    - vars/personal.yml

  tasks:
    - name: Tap homebrew repositories
      homebrew_tap: tap={{ item }}
      with_items: "{{ homebrew_taps }}"

    - name: Install apps via `brew cask`
      homebrew_cask: name={{ item }} # install_options="appdir={{ homebrew_cask_appdir }}"
      with_items: "{{ homebrew_cask_apps }}"

    - name: Install configured homebrew packages
      homebrew: name={{ item }} state=latest
      with_items: "{{ homebrew_packages }}"
