---
################################################################################
# dnsmasq config                                                               #
################################################################################

- name: Create /etc/resolver directory
  become: yes
  file:
    path: /etc/resolver
    state: directory

- name: Add *.loc resolver
  become: yes
  lineinfile:
    state: present
    line: nameserver 127.0.0.1
    create: yes
    dest: /etc/resolver/loc
    owner: root
    group: wheel

- name: Resolve *.loc to localhost
  lineinfile:
    state: present
    line: address=/.loc/127.0.0.1
    create: yes
    dest: /usr/local/etc/dnsmasq.conf
  notify: restart dnsmasq

################################################################################
# nvm config                                                                   #
################################################################################

- name: Create ~/.nvm directory
  file:
    path: ~/.nvm
    state: directory

- name: Add symbolic link to nvm.sh
  file:
    src: /usr/local/opt/nvm/nvm.sh
    dest: ~/.nvm/nvm.sh
    state: link

################################################################################
# services                                                                     #
################################################################################

- name: List running services
  command: sh -s "brew services list | grep started"
  register: running_services_list
  changed_when: false

- name: Start services
  command: brew services start {{ item.name }}
  become: "{{ item.root }}"
  with_items: "{{ dev.services }}"
  when: "'{{ item.name }}' not in running_services_list.stdout"
