---
################################################################################
# dnsmasq config                                                               #
################################################################################

- name: Create /etc/resolver directory
  become: yes
  file:
    path: /etc/resolver
    state: directory

- name: Add *.dev resolver
  become: yes
  lineinfile:
    state: present
    line: nameserver 127.0.0.1
    create: yes
    dest: /etc/resolver/dev
    owner: root
    group: wheel

- name: Resolve *.dev to localhost
  lineinfile:
    state: present
    line: address=/.dev/127.0.0.1
    create: yes
    dest: /usr/local/etc/dnsmasq.conf
  notify: restart dnsmasq

################################################################################
# Apache config                                                                #
################################################################################

- name: Ensure ~/Sites exists
  file:
    path: ~/Sites
    state: directory
    follow: yes

- name: Ensure Virtual Hosts directory exists
  file:
    path: /usr/local/etc/apache2/2.4/vhosts
    state: directory
    follow: yes

- name: Configure Apache
  become: yes
  lineinfile:
    dest: /usr/local/etc/apache2/2.4/httpd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_configuration_items }}"
  notify: restart apache

- name: Remove PHP modules
  lineinfile:
    dest: /usr/local/etc/apache2/2.4/httpd.conf
    regexp: "^#?LoadModule php[5|7]_module*"
    state: absent

- name: Add PHP 5 module
  lineinfile:
    dest: /usr/local/etc/apache2/2.4/httpd.conf
    regexp: "^LoadModule php5_module /usr/local/lib/libphp5.so"
    insertafter: "^LoadModule rewrite_module libexec/mod_rewrite.so"
    line: "LoadModule php5_module /usr/local/lib/libphp5.so"
    state: present

- name: Add PHP 7 module
  lineinfile:
    dest: /usr/local/etc/apache2/2.4/httpd.conf
    regexp: "^#LoadModule php7_module /usr/local/lib/libphp7.so"
    insertafter: "^LoadModule php5_module /usr/local/lib/libphp5.so"
    line: "#LoadModule php7_module /usr/local/lib/libphp7.so"
    state: present

- name: Add apache vhosts configuration
  template:
    src: "vhosts.conf.j2"
    dest: "/usr/local/etc/apache2/2.4/extra/httpd-vhosts.conf"
    mode: 0644
  notify: restart apache

- name: Add apache php handler
  template:
    src: "php.conf.j2"
    dest: "/usr/local/etc/apache2/2.4/extra/httpd-php.conf"
    mode: 0644
  notify: restart apache

################################################################################
# PHP config                                                                   #
################################################################################

- name: PHP configuration
  ini_file:
    dest: /usr/local/etc/php/{{ item[1] }}/php.ini
    section: "{{ item[0].section }}"
    option: "{{ item[0].option }}"
    value: "{{ item[0].value }}"
  with_nested:
    - "{{ php_configuration_items }}"
    - ["5.5", "5.6", "7.0", "7.1"]
  notify: restart apache

################################################################################
# nvm config                                                                   #
################################################################################

- name: Create ~/.nvm directory
  file:
    path: ~/.nvm
    state: directory

- name: Add symbolic link to nvm.sh
  file:
    src: /usr/local/opt/nvm/nvm.sh
    dest: ~/.nvm/nvm.sh
    state: link

################################################################################
# services                                                                     #
################################################################################

- name: List running services
  command: sh -s "brew services list | grep started"
  register: running_services_list
  changed_when: false

- name: Start services
  command: brew services start {{ item.name }}
  become: "{{ item.root }}"
  with_items: "{{ dev.services }}"
  when: "'{{ item.name }}' not in running_services_list.stdout"
