---
homebrew_cask_appdir: /Applications
install_cask_apps: yes
dev:
  php_versions:
    - php55
    - php56
    - php70
    - php71

  php_extensions:
    - xdebug
    - intl
    - redis
    - imagick
    - mcrypt
    - opcache
    - apcu
    - yaml

  homebrew_taps:
    - caskroom/cask
    - caskroom/fonts
    - homebrew/apache
    - homebrew/php
    - homebrew/versions
    - homebrew/services

  homebrew_packages:
    - tree
    - wget
    - fish
    - bash
    - pv
    - ssh-copy-id
    - redis
    - mysql56
    - composer
    - imagemagick
    - elasticsearch17
    - heroku-toolbelt
    - node
    - nvm
    - dnsmasq
    - homebrew/dupes/rsync

  homebrew_cask_apps:
    - atom
    - cocoarestclient
    - docker
    - firefox
    - google-chrome
    - phpstorm
    - iterm2
    - java
    - skype
    - slack
    - vagrant
    - virtualbox
    - wkhtmltopdf
    - sequel-pro
    - robomongo
    - vmware-fusion
    - font-fira-code

  npm_packages:
    - gulp

  gem_packages:
    - hologram

  services:
    - name: dnsmasq
      root: true
    - name: httpd24
      root: true
    - name: mysql56
      root: false
    - name: elasticsearch17
      root: false
    - name: redis
      root: false
