---
- name: "Playing fish shell plugins via fisher"
  hosts: localhost
  connection: local

  vars_files:
    - ../vars/fisher.yml

  tasks:
    - name: Install fisher
      shell: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
      args:
        creates: ~/.config/fish/functions/fisher.fish

    - name: Install fisher deps
      shell: fisher install {{ item[0] }}
      args:
        executable: /opt/homebrew/bin/fish
      with_items: "{{ fisher_packages }}"
