---
- name: "Playing PHP versions and extensions"
  hosts: localhost
  connection: local

  vars_files:
    - ../vars/php.yml

  tasks:
    ################################################################################
    # PHP install                                                                  #
    ################################################################################

    - name: Switch PHP script
      shell: "curl -L https://gist.githubusercontent.com/rhukster/f4c04f1bf59e0b74e335ee5d186a98e2/raw/791fda77946ab2dbd053d7f27e9237aaf7392c4b/sphp.sh > /usr/local/bin/sphp;"
      args:
        creates: "/usr/local/bin/sphp"

    - name: Execution attributes for sphp script
      file:
        path: "/usr/local/bin/sphp"
        mode: "0755"

    ################################################################################
    # PHP config                                                                   #
    ################################################################################

    - name: PHP configuration
      ini_file:
        dest: /opt/homebrew/etc/php/{{ item[1].version }}/php.ini
        section: "{{ item[0].section }}"
        option: "{{ item[0].option }}"
        value: "{{ item[0].value }}"
      with_nested:
        - "{{ php_configuration_items }}"
        - "{{ php_versions }}"
      loop_control:
        label: "Setting [{{ item[0].section }}] {{ item[0].option }} to {{ item[0].value }} for PHP {{ item[1].version }}"

    - name: Switch PHP to version 7.3
      command: "sphp 8.0 -s"

    ################################################################################
    # Symfony CLI                                                                  #
    ################################################################################

    - name: Install Symfony CLI
      shell: curl -sS https://get.symfony.com/cli/installer | bash
      args:
        creates: "{{ lookup('env','HOME') }}/.symfony/bin/symfony"

    - name: Make Symfony CLI available globally
      copy:
        src: "{{ lookup('env','HOME') }}/.symfony/bin/symfony"
        dest: /usr/local/bin/symfony
        mode: u=rwx,g=rx,o=rx

    - name: Install nss
      homebrew: name=nss state=latest

    - name: Install Symfony Local Server certificate
      shell: symfony server:ca:install
      ignore_errors: yes

    - name: Start Symfony Local Proxy
      shell: symfony local:proxy:start
      ignore_errors: yes
